### ISSUE TITLE
Incorporate upstream

### ISSUE THREAD

**Issue by ddevault** [saber-nyan/kernel-modules-hook#4]
Have you asked if Arch Linux would be interested in incorporating your work into the official kernel packages?

**Comment by saber-nyan** [comment]
Nope. Btw it would be more logical for Arch maintainers to add this set of scripts to the standard distribution package.

**Comment by ddevault** [comment]
Have you considered sending the relevant maintainers a patch for their PKGBUILD?

**Comment by saber-nyan** [comment]
No, I didn't. Basically, because I'm not sure about the license for this package: hooks are taken from Reddit.

**Comment by craftyguy** [comment]
Where on reddit? The original author(s) may give it a FOSS license if asked..

**Comment by saber-nyan** [comment]
https://github.com/saber-nyan/kernel-modules-hook/blob/eabd3ea8ebe6486739341fbc4061dab938624867/PKGBUILD#L2
The [topic](https://www.reddit.com/r/archlinux/comments/4zrsc3/keep_your_system_fully_functional_after_a_kernel/d6yin0r/) is over two years old, but it is not so important. If someone can contact [ephemient](https://www.reddit.com/user/ephemient), it will be cool, since I don’t want to create an account on Reddit.

**Comment by craftyguy** [comment]
Since that username seems to be somewhat unique, and there's a ephemient user on github....

@ephemient: if you are the ephemient that created the pacman hooks used in this project, we would like to know what license you released it under. Bonus points if it's a FLOSS license :smile:

**Comment by ephemient** [comment]
Yes, that's me. I've added an Unlicense to my copy: https://gist.github.com/ephemient/1b8a253b1437f548f61f4f463e51f60e

**Comment by saber-nyan** [comment]
Thanks!

**Comment by shibumi** [comment]
Hi,
I am Arch Linux TU. I would like to fork this to our github organisation and move the AUR package to community. Are there any objections against this step from your side?

https://bugs.archlinux.org/task/16702

Feel free to support my request in the bug tracker as well.

**Comment by saber-nyan** [comment]
@shibumi
Yes, I will only be glad to transfer this package to the community repository. I have little time to maintain it because of my studies...

**Comment by Strykar** [comment]
@shibumi 10 years and counting on that bug, no rush I guess. I'll install this from aur :)

**Comment by craftyguy** [comment]
Is there still a chance of promoting this to the community repo any time soon?

**Comment by Hexhu** [comment]
What is blocking this package from being transferred from AUR to community? It perfectly solves the problem and does no harm... @shibumi

**Comment by shibumi** [comment]
@Hexhu my lack of time in combination with a full head lead to me forgetting about this issue.

But, fear no more, adventurer! The waiting is over: https://archlinux.org/packages/community/any/kernel-modules-hook/

**Comment by shibumi** [comment]
@saber-nyan feel free to close this issue + add a note in the readme about installing it
