### ISSUE TITLE
Nov 2019 changes to kernel packages and mkinitcpio hooks

### ISSUE THREAD

**Issue by Strykar** [saber-nyan/kernel-modules-hook#8]
Is this affected by https://www.archlinux.org/news/new-kernel-packages-and-mkinitcpio-hooks/

**Comment by saber-nyan** [comment]
Yep, and should be fixed in #7. But not tested.

**Comment by Strykar** [comment]
I upgraded, will report back after next kernel update. Thanks!

**Comment by cptpcrd** [comment]
The hooks did not work properly on the `5.3.11-arch1-1` upgrade. I believe that changing the `Operation`  to `Install` in both hooks will fix it (have done some partial testing). It looks like pacman classifies it as an `Install` because the file path changes.
